Q: How did you get interested in the Book of Revelation, and how long have you be studying the End Times?
A: I read The Late Great Planet Earth when I was about 20 years old, and that’s how I got started. I was a brand-new Christian then, and it was just fascinating to me that the Bible told the future. When I read that book, it documented all the prophesies that had come true and the ones that were going to come true. That got me addicted to it, and I read book after book after book. I didn’t know the Bible well at that time, but End Time prophecy was actually one of the ways that I got into the Bible. I’ve been studying it for 46 years now.

Q: How did you go from studying the End Times to writing the book, Tipping Point?
A: As a pastor for many years, I pretty much preached a series every year or two on the End Times. I amassed a lot of information that way and I really wanted to write a book on this subject. I did the Tipping Point series at Gateway Church back in 2014. Then I did it on Daystar, and that really went viral. That’s when I decided to write the book.

Q: So, let’s talk about the End Times. When did the end of the Last Days begin, and how do we know this?
A: There’s two measures. One is in Daniel 9. The Angel Gabriel told Daniel that 490 prophetic years had been determined for the Jews and for Jerusalem, and he said from the going forth of the decree until Messiah the Prince is cut off, but not for himself, there’s going to be 483 prophetic years. And on March 14, 445 B.C., Artaxerxes Longemanus declared that the Jews could go back under Nehemiah and rebuild Jerusalem. So that started the clock. So the official end began on March 14, 445 B.C. And by the way if you go 483 years from the decree using a 355-day yearly cycle because the Jews used a lunar calendar, that’s April 6, 32 A.D. That’s Palm Sunday when Jesus rode in on a colt and began His death march to the cross. That prophecy was exactly fulfilled. So that’s when the end began. We have 7 more prophetic years left, and that’s the tribulation. That will complete the 490 years. The Last Days began on May 14, 1948. In Joel 3, God says, “In those days and at the same time when I bring back the captives of Judah and Jerusalem, I will enter into Judgement with the nations on account of my people, my heritage Israel whom they’ve scattered among the nations, and they’ve divided up my land.” And so God says at the same time He brings back the Children of Israel, that’s when the Last Days will begin.

Q: We are seeing a growing trend of anti-Semitism. Why is that also a sign of the End Times?
A: Zachariah 12 says, I’m going to make Jerusalem a very heavy stone for all the people, and anyone who tries to move it will be hurt. It says in Joel 3 that God will enter into judgement against the nations in the Valley of Jehoshaphat. This Valley is between the Temple Mount and the Mount of Olives. And so, at the Second Coming of Jesus when His feet touch the Mount of Olives, He enters into Judgement right there with the world. Revelation 19 and 20 detail it very graphically. The entire world at that point has gathered against the Jews and against Jerusalem. What they’re trying to do at that point is force the Jews to give up Jerusalem, or at least East Jerusalem, and the Lord shows up and fights against them. COVID-19 has even increased anti-Semitism because a lot of people are blaming the Jews for COVID-19. Anti-Semitism is rising at Harvard University, Princeton University, and many other universities across America. It’s getting so bad in Europe that they’re having to leave France and Germany and go back to either Israel or the United States. So, it is a major sign of the End Times. For example, the United Nations has censured Israel more than all other nations combined. In fact, we found out that President Obama was trying to force a two-state solution in Israel before he left office and didn’t pull it off. And so the rising hatred of the Jews is a major sign of the End Times.

Q: How is the world currently at a Tipping Point, and how does this point us to the final chapter of the End Times?
A: In Matthew 24, Jesus said there would be destress among nations with perplexity. Perplexity means there are no answers. We have a financial crisis in the world. It’s masked a lot through debt. America alone is now $27 Trillion in debt, and that’s rising very rapidly. And the dollar is dropping right now because of that. And so, we see an economic crisis. We see COVID-19, pandemics, famines, wars and rumors of wars. We see conflict on just about any continent you can think of.

I think the greatest crisis, though, is the moral crisis that we’re seeing – the rise in violence, the rise in immorality, the falling away of any traditional morality. It is absolutely shocking to me that we have gotten to the point where people believe that you can actually change your sex or allow a 10 year old child to make their own choice as to what sex they are and to go through with all the transitioning, which is a farce. I think, given any category, we’re in a crisis.

Q: Let’s talk about the rapture… Some say it isn’t in the Bible – what do you think?
A: 1 Thessalonians 4 is the most graphic Scripture in the Bible of the rapture, “The Lord will descend from heaven with a shout, with the voice of an archangel and the trumpet of God. The dead in Christ will rise first, and we who are alive and remain will be caught up to meet the Lord in the clouds in the air.” The phrase “caught up” here is the Greek word Harpazo, but it’s also the Latin word Rapturo. That’s where we get our word rapture. People say it’s not a biblical word, but it is if you have a Latin bible! It’s a very biblical word. Jesus described the rapture in Luke 17, and He was talking about His return would be like the Days of Noah and the Days of Lot – buying and selling, marriage and given in marriage, planning and building. In that context, He said that in that day there would be two men standing in a field, one taken and one left. The word “taken” there means to “receive to yourself.” He said there will be two people in bed, one taken and one left.

In John 14, Jesus was using wedding language. And all the disciples were Galilean; they had all the same marriage customs. Jesus said, “In My Father’s house, there are many mansions. I’m going away to prepare a place for you, and if it wasn’t true, I would tell you. And as sure as I go away, I’m going to come back to receive you unto Myself. So that where I am, you may be also.” Well, that’s what a groom did. A Jewish groom who was betrothed to his bride would go away to his father’s house for about a year, and he would build a place for he and his bride. Then when his father told him too, the groom would comeback at an unexpected hour, typically in the middle of the night, and got his bride and took her back. There’s going to be a rapture, and it’s going to happen in the twinkling of an eye.

Q: Another common questions about the End Times is, who is the Antichrist? What does the Bible tell us about him?
A: We absolutely know for sure that he is going to come from the old Roman Empire based on Daniel 9 and Luke 21. But here’s what a lot of people don’t know… Many people look at the Roman Empire as being Europe. That is correct, but you have to remember during the time of Jesus, the Roman Empire also included the Middle East and Northern Africa. Antichrist is a word only used by the Apostle John. There are many names and titles used for the Antichrist in the Old Testament and New Testament. And so, one of the titles for the Antichrist is The Assyrian. In the book of Micah and twice in the book of Isaiah he’s referred to as The Assyrian. I’m reading a book right now called The Assyrian Antichrist by Joel Richardson, and he documents very convincingly that the Antichrist will be Muslim. He talks a lot about the End Time theology of the Muslims. It’s very much like ours, except in our case it’s the Antichrist and the false prophet. In their case, it’s the Mahdi and Jesus. In his book, he also talks about beheading. Revelation 20 says, “Because they wouldn’t worship the Antichrist or take his mark and because of their testimony of Jesus, they were beheaded.” That’s a trademark of Islam.

Q: After the Great Tribulation, the Bible says we’ll see the Millennial reign of Christ. What will that be like, and what is the purpose of this period?
A: There were seven days of creation. For six days, God worked. On the seventh, he rested. And Isaiah says God declares the end from the beginning. In the beginning, God was declaring 7000 years of human history. With God, a day is as a thousand year, and a thousand years as a day. So, there are going to be 6000 years of human history, and we’re there right now, followed by 1000-year rule of Christ when the Earth rests and mankind rests. We haven’t rested for 6000 years. When Jesus comes at the second coming – Revelation 19 and 20 – He sets up His throne in Jerusalem, and He rules the nations. Now there’s no more grace at that point. The second coming is the end of grace. The age of grace officially ends at the end of the Tribulation. People can still be saved during the Tribulation. During the Millennium, no one gets saved. And part of the purpose of the Millennium is to reward the Church in ruling and reigning. We finally get dominion over the Earth under Jesus, and we’re ruling and reigning. We have perfect bodies. We’re perfect. We don’t need anymore grace. We’re the wife of Jesus. We finally get back to where God wanted us to be – with Him in a perfect environment. The people on earth though are being punished. You have to remember that everyone alive on earth during the Millennium survived the Tribulation, and it says in Revelation, they sought death, and it escaped them. They literally are trying to commit suicide, and God won’t let them. Because what God is saying is, “No, you’re going to live under a thousand years of my rule.” Now imagine for the rebellious people in the world today – and there’s a lot of them – imagine how terrible it would be to live under the iron-rod rule of Jesus. You only do what Jesus tells you to do, and if you don’t, there’s no grace. All during the Millennium, Satan is bound. At the end, he is loosed, and he goes out and deceives the nations. And they march on Jerusalem to kill us and Jesus. So, they hate us. Their response to a thousand-year rule of Jesus isn’t “This is wonderful.” Their response is we’re going to kill you. So, it’s going to be bad, but at the end of the Millennium, the old heavens and earth will be destroyed. There will be new heavens and a new earth, and the New Jerusalem will come down out of heaven. And then we’ll have perfection. The earth is perfect, and there’s never been a sin committed on the newly constructed earth.

Q: What should we be doing to prepare for the rapture and the Second Coming of Jesus?
A: We should prepare by having a relationship with Jesus. Just be living for God! You don’t have to be perfect by any means, but just be living for God and have a relationship with Jesus where you’re ready to see Him.

 