<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,600,700&amp;amp;subset=latin-ext" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('public/frontend')}}/plugins/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{asset('public/frontend')}}/fonts/Linearicons/Linearicons/Font/demo-files/demo.css">
    <link rel="stylesheet" href="{{asset('public/frontend')}}/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{asset('public/frontend')}}/plugins/owl-carousel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="{{asset('public/frontend')}}/plugins/owl-carousel/assets/owl.theme.default.min.css">
    <link rel="stylesheet" href="{{asset('public/frontend')}}/plugins/slick/slick/slick.css">
    <link rel="stylesheet" href="{{asset('public/frontend')}}/plugins/nouislider/nouislider.min.css">
    <link rel="stylesheet" href="{{asset('public/frontend')}}/plugins/lightGallery-master/dist/css/lightgallery.min.css">
    <link rel="stylesheet" href="{{asset('public/frontend')}}/plugins/jquery-bar-rating/dist/themes/fontawesome-stars.css">
    <link rel="stylesheet" href="{{asset('public/frontend')}}/plugins/select2/dist/css/select2.min.css">
    <link rel="stylesheet" href="{{asset('public/frontend')}}/css/style.css">
    <link rel="stylesheet" href="{{asset('public/frontend')}}/css/market-place-1.css">